### PR TITLE
Update decode.go

### PR DESCRIPTION
**Pull request by neshala**
Bugfix when input does not have len of 32

### CODE REVIEW

**Comment by ferranbt** [comment]
Could you provide an example of the function call when this happens?

'decode' is used to decode both simple types (uint, bool...) and composite types (tuples, arrays...). Does this happen when you want to decode to a simple type or when you want to decode a tuple (the function params are represented as a tuple). Since you want to return map[string]interface{} I would assume it is the second one. Do you have a function without params perhaps?

**Comment by neshala** [comment]
Here is code that i am using:

```go
        cFactory := contract.NewContract(addr, abiFactory, client)

	// pack path into slice of addresses
	var addresses []web3.Address
	for _, t := range paths {
		if !isValidAddress(t) {
			err := errors.New("invalid address: " + t)
			return def, err
		}

		addresses = append(addresses, web3.HexToAddress(t))
	}

	if len(addresses) < 2 {
		err := errors.New("addresses must have at least 2 items")
		return def, err
	}

	data, err := cFactory.Call("getAmountsOut", web3.Latest, val, addresses)
	if err != nil {
		return def, err
	}
```


ABI and address of contact can be taken from here:
https://bscscan.com/address/0x05ff2b0db69458a0750badebc4f9e13add608c7f#code


Instead of map[string]interface{} we can simply return nil, maybe that has more sense, since it will not be working data.

Error occurs just sometimes, because input params are different all the time. val is BigInt

I think only issue not covered is that input can be string with less than 32 char so this can not be done: 
```go
data = input[:32]
```

**Comment by ferranbt** [comment]
I see, could you provide the specific inputs that cause the error? Because in your function both inputs should be okay (big int, array of fixed size). The issue with less than 32 char string I think it is a different one (I will test it now).

**Comment by ferranbt** [comment]
I could not reproduce the less than 32 char string issue. There are already test for different sizes of strings like https://github.com/umbracle/go-web3/blob/master/abi/encoding_test.go#L196

**Comment by neshala** [comment]
This bug is not easy to reproduce, because it occurs from time to time with various input params.
I am running it inside of goroutines, but each routine have its own instance of NewContract, so there should not be a collision 

For my code above fix that I have suggested solving the issue every time, without that after few minutes of running my code I receive a panic error described earlier:
panic: runtime error: slice bounds out of range [:32] with capacity 0

**Comment by ferranbt** [comment]
Could you try again with the current master. I merged #62 which fixes an issue like the one you describe (reading 32 bytes from an empty data). However, in this case it happens when it tries to ParseLogs from a deposit and not from a Call like in your example.

**Comment by ferranbt** [comment]
I am closing this PR in favor of #76. I was able to reproduce the bug, you were most likely calling a contract with a function that did not exists. Thus, the response was empty. Now, contract raises an error and abi includes some safe checks to avoid this.

**Pull request closed without merging**
